### PR TITLE
Fix null pointer access when iterating over empty arrays

### PR DESCRIPTION
**Pull request by s-ludwig**
The PropTable.table field is a RandAA, which is a class and thus does not exhibit the more forgiving interface as built-in AAs.

This PR also fixes the CI stage for running the test262 test suite, which appears to have been broken for a while.

### CODE REVIEW

**Comment by WalterBright** [comment]
thank you!

**Comment by WalterBright** [comment]
What about the failing test?

**Comment by s-ludwig** [comment]
Looks like the python2 executable isn't available by default for GitHub actions anymore. I'll see if I can quickly fix that.

**Comment by s-ludwig** [comment]
Finally got it to complete again. There were several issues:
- Python 2 not being available, I first tried to install Python 2 manually, which didn't quite work, so  instead the code is now adjusted for Python 3
- Some test log output caused grep to recognize the log as binary and in turn to not output the matched text
- For some reason the `dmdscript:ds` binary, which used by the test suite, crashes when being generated by DMD - I worked around that for now by compiling with LDC
- The fix makes some additional test cases pass, so the number needed to be bumped up

**Comment by s-ludwig** [comment]
Fixed another small issue in `RandAA` that came up.

**Pull request merged**
